
########### 10_Spatial_Interaction_Validation.R #########
library(Seurat)
library(dplyr)
library(proxy)
library(mgcv)
library(CellChat)

set.seed(42) 

st_obj <- readRDS("ST_integrated_final.rds")
card_obj <- readRDS("CARD_S11_obj.rds") # Load representative CARD obj

# Extract coordinates and proportions
coords_raw <- card_obj@spatial_location
props <- card_obj@Proportion_CARD

# Scale coordinates to um
x_range <- max(coords_raw[,1]) - min(coords_raw[,1])
scale_factor <- 6800 / x_range
coords <- coords_raw * scale_factor

# Define dominant cell identities (Proportion > 0.1 threshold)
max_cols <- colnames(props)[max.col(props, ties.method = "first")]
max_props <- apply(props, 1, max)

ci_idx <- which(max_cols == "16" & max_props > 0.1) 
pmc_idx <- which(max_cols == "4" & max_props > 0.1)


# 1. Spatial colocalization validation (500 permutations)
# Calculate true distance from CI to nearest PMC
dist_mat <- proxy::dist(coords[ci_idx, ], coords[pmc_idx, ])
true_min_dists <- apply(dist_mat, 1, min)

# Methods: Background distribution generated by random permutation (500 iterations)
n_iterations <- 500
random_min_dists <- numeric()

for (i in 1:n_iterations) {
 # Randomly shuffle PMC positions across all spots to break spatial structure
 rand_pmc <- sample(1:nrow(coords), length(pmc_idx))
 rand_dist_mat <- proxy::dist(coords[ci_idx, ], coords[rand_pmc, ])
 random_min_dists <- c(random_min_dists, apply(rand_dist_mat, 1, min))
}

# Methods: Significance determined using Wilcoxon rank-sum test
wilcox_res <- wilcox.test(true_min_dists, random_min_dists, alternative = "less")

spatial_dist_df <- data.frame(
 Distance = c(true_min_dists, random_min_dists),
 Group = factor(c(rep("PMC", length(true_min_dists)), 
                  rep("Random", length(random_min_dists))), levels = c("PMC", "Random"))
)

write.table(spatial_dist_df, "Spatial_Colocalization_Validation.txt", sep="\t", quote=FALSE, row.names=FALSE)
message("Wilcoxon p-value for colocalization: ", wilcox_res$p.value)



# 2. LR Interaction Potential and GAM Decay Fitting
# Extract expression
expr_data <- GetAssayData(st_obj, slot = "data", assay = "Spatial")

# Define target pairs (Subset from full list)
ligands <- c("Sgal02g028120", "Sgal02g018240")
receptors <- c("Sgal10g001460", "Sgal08g012010")

gam_predictions_list <- list()

for (i in 1:length(ligands)) {
 lig <- ligands[i]
 rec <- receptors[i]
 
 if(!lig %in% rownames(expr_data) | !rec %in% rownames(expr_data)) next
 
 # Product of ligand and receptor expression levels
 l_vec <- expr_data[lig, ]
 r_vec <- expr_data[rec, ]
 
 # Get pairs within a 300 um radius threshold
 full_dist_mat <- proxy::dist(coords[pmc_idx, ], coords[ci_idx, ])
 valid_indices <- which(full_dist_mat < 300, arr.ind = TRUE)
 
 if(nrow(valid_indices) < 10) next
 
 distances <- full_dist_mat[valid_indices]
 interaction_scores <- l_vec[pmc_idx[valid_indices[, 1]]] * r_vec[ci_idx[valid_indices[, 2]]]
 
 # Filter positive interactions
 model_df <- data.frame(Distance = distances, Score = interaction_scores)
 model_df <- model_df[model_df$Score > 0, ]
 
 if (nrow(model_df) > 50) {
  # Methods: A Generalized Additive Model (GAM) was used to fit the decay curve
  # bs = "cs" applies shrinkage cubic regression splines
  gam_model <- mgcv::gam(Score ~ s(Distance, bs = "cs"), data = model_df)
  
  # Predict the smoothed curve
  pred_dist <- seq(0, 300, length.out = 100)
  pred_res <- predict(gam_model, newdata = data.frame(Distance = pred_dist), se.fit = TRUE)
  
  gam_predictions_list[[paste0(lig, "_", rec)]] <- data.frame(
   Ligand = lig,
   Receptor = rec,
   Distance = pred_dist,
   Predicted_Score = pred_res$fit,
   SE = pred_res$se.fit
  )
 }
}

gam_decay_results <- do.call(rbind, gam_predictions_list)
write.table(gam_decay_results, "LR_GAM_Decay_Predictions.txt", sep="\t", quote=FALSE, row.names=FALSE)


# 3. CellChat Integration & Comparison
# Assuming cellchat_list contains individually processed objects
# cellchat_list <- readRDS("cellchat_list.rds")

# cellchat_com <- mergeCellChat(cellchat_list, add.names = names(cellchat_list))
# diff_interactions <- compareInteractions(cellchat_com, show.legend = FALSE, group = c(1,2))

# print("CellChat processing complete.")